name: cedar-mkdocs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - mkdocs-material-extensions=1.0.3
  - pymdown-extensions=9.6
  - sphinx_rtd_theme=1.0.0
  - pip
  - pip:
      - mkdocs-material==8.5.6
      - mkdocs-markdownextradata-plugin==0.2.5
      - mkdocs==1.4.1
