site_name: CEDAR
theme:
  name: material
  features:
    - navigation.indexes

markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: false
  - markdown.extensions.attr_list

plugins:
  - markdownextradata: { }
  - search: { }

extra:
  page:
    cedarw: "CEDAR Workbench"
    cdeb: "CDE Browser"
    fb: "caDSR Form Builder"

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/metadatacenter/cedar-mkdocs
edit_uri: edit/develop/docs/

nav:
  - Home: index.md

  - User Guide:
      - user-overview/index.md
      - CEDAR Basics:
          - user-guide/cedar-basics/index.md
          - user-guide/accounts-and-logging-in.md
          - user-guide/your-cedar-workspace.md
          - user-guide/description-of-a-template.md
          - user-guide/filling-out-metadata.md
          - user-guide/building-basic-templates.md
          - user-guide/more-fair-templates.md
          - user-guide/finding-resources.md
          - user-guide/managing-resources.md
          - user-guide/sharing-resources.md
          - user-guide/artifact-versioning.md
      - Advanced Topics:
          - user-guide/advanced-topics/index.md
          - user-guide/viewing-resource-information.md
          - user-guide/understanding-the-suggestion-system.md
          - user-guide/cedar-identifiers-and-iris.md
          - user-guide/cedars-api.md
          - user-guide/working-with-cdes.md
          - user-guide/cedar-for-cadsr.md
      - user-guide/pages/faq.md
      - user-guide/pages/glossary.md

  - Install Guides:
      - install-overview/index.md
      - Developer Install:
          - install-developer/overview/index.md
          - install-developer/prerequisites.md
          - install-developer/configuration.md
          - install-developer/cedar-cli-and-scripts.md
          - install-developer/building-the-code.md
          - install-developer/ssl-certificates.md
          - install-developer/infrastructure-services.md
          - install-developer/microservices.md
          - install-developer/frontends.md

      - Docker Install:
          - install-docker-eval/overview/index.md
          - install-docker-eval/prerequisites.md
          - install-docker-eval/configuration.md
          - install-docker-eval/cli-and-scripts.md
          - install-docker-eval/one-time-setup.md
          - install-docker-eval/components.md
          - install-docker-eval/evaluate-cedar.md

      - CEDAR Embeddable Editor:
          - cedar-embeddable-editor/intro/index.md
          - cedar-embeddable-editor/try-out.md

  - Developer Guide:
      - developer-overview/index.md
      - CEDAR Repository Model: https://metadatacenter.org/tools-training/outreach/cedar-template-model
      - developer-guide/template-element-and-field-instances.md
      - developer-guide/template-element-and-fields.md
      - developer-guide/cedar-rest-apis.md

  - YAML Specification:
      - yaml-spec/index.md
      - yaml-spec/cedar-model.md
      - yaml-spec/core-structure.md
      - yaml-spec/templates-core.md
      - yaml-spec/elements-core.md
      - yaml-spec/fields-core.md
      - yaml-spec/field-types.md
      - yaml-spec/value-constraints.md
      - yaml-spec/versioning.md
      - yaml-spec/provenance.md
      - yaml-spec/annotations.md
      - yaml-spec/instances.md
      - yaml-spec/examples.md
      - yaml-spec/appendices.md

  - Operations and Management: operations-and-management.md
